Update eks anywhere homebrew formula to v0.7.2
aws/homebrew-tap pull request #277
Opened 2022-03-01 19:19 UTC by mrajashree

*Issue #, if available:*

*Description of changes:*
This PR updates the  AWS homebrew tap's EKS Anywhere formula to the latest [release v0.7.2](https://github.com/aws/eks-anywhere/releases/tag/v0.7.2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-01 20:23 UTC, rothgar commented
I'm assuming you need to update the SHAs too

2022-03-17 20:47 UTC, efekarakus approved these changes

2022-03-17 20:48 UTC, efekarakus requested changes
waiting on shas to be updated*

2022-03-17 22:56 UTC, mrajashree commented
@rothgar @efekarakus updated it

2022-03-18 01:07 UTC, efekarakus approved these changes

2022-03-18 01:08 UTC, merged